const departments = [
  "Apparel & Fashion Design",
  "Applied Mathematics & Computational Sciences",
  "Applied Science",
  "Automobile Engineering",
  "Bio-technology",
  "Biomedical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Computer Science & Engineering",
  "Electronics & Communication Engineering",
  "Electrical & Electronics Engineering",
  "English",
  "Fashion Technology",
  "Humanities",
  "Instrumentation & Control Systems Engineering",
  "Information Technology",
  "Mathematics",
  "Computer Applications",
  "Mechanical Engineering",
  "Metallurgical Engineering",
  "Physics",
  "Production Engineering",
  "Robotics & Automation Engineering",
  "Textile Technology",
  "Management Sciences",
  "Library",
  "Physical Education",
];

export { departments };